from enum import StrEnum

class TarotCard(StrEnum):
    THE_FOOL: str = "0"
    THE_MAGICIAN: str = "1"
    THE_HIGH_PRIESTESS: str = "2"
    THE_EMPRESS: str = "3"
    THE_EMPEROR: str = "4"
    THE_HIEROPHANT: str = "5"
    THE_LOVERS: str = "6"
    THE_CHARIOT: str = "7"
    STRENGTH: str = "8"
    THE_HERMIT: str = "9"
    WHEEL_OF_FORTUNE: str = "10"
    JUSTICE: str = "11"
    THE_HANGED_MAN: str = "12"
    DEATH: str = "13"
    TEMPERANCE: str = "14"
    THE_DEVIL: str = "15"
    THE_TOWER: str = "16"
    THE_STAR: str = "17"
    THE_MOON: str = "18"
    THE_SUN: str = "19"
    JUDGEMENT: str = "20"
    THE_WORLD: str = "21"

    ACE_OF_CUPS: str = "ac"
    TWO_OF_CUPS: str = "2c"
    THREE_OF_CUPS: str = "3c"
    FOUR_OF_CUPS: str = "4c"
    FIVE_OF_CUPS: str = "5c"
    SIX_OF_CUPS: str = "6c"
    SEVEN_OF_CUPS: str = "7c"
    EIGHT_OF_CUPS: str = "8c"
    NINE_OF_CUPS: str = "9c"
    TEN_OF_CUPS: str = "10c"
    PAGE_OF_CUPS: str = "pc"
    KNIGHT_OF_CUPS: str = "kc"
    QUEEN_OF_CUPS: str = "qc"
    KING_OF_CUPS: str = "rc"


    ACE_OF_PENTACLES: str = "ad"
    TWO_OF_PENTACLES: str = "2d"
    THREE_OF_PENTACLES: str = "3d"
    FOUR_OF_PENTACLES: str = "4d"
    FIVE_OF_PENTACLES: str = "5d"
    SIX_OF_PENTACLES: str = "6d"
    SEVEN_OF_PENTACLES: str = "7d"
    EIGHT_OF_PENTACLES: str = "8d"
    NINE_OF_PENTACLES: str = "9d"
    TEN_OF_PENTACLES: str = "10d"
    PAGE_OF_PENTACLES: str = "pd"
    KNIGHT_OF_PENTACLES: str = "kd"
    QUEEN_OF_PENTACLES: str = "qd"
    KING_OF_PENTACLES: str = "rd"

    ACE_OF_SWORDS: str = "as"
    TWO_OF_SWORDS: str = "2s"
    THREE_OF_SWORDS: str = "3s"
    FOUR_OF_SWORDS: str = "4s"
    FIVE_OF_SWORDS: str = "5s"
    SIX_OF_SWORDS: str = "6s"
    SEVEN_OF_SWORDS: str = "7s"
    EIGHT_OF_SWORDS: str = "8s"
    NINE_OF_SWORDS: str = "9s"
    TEN_OF_SWORDS: str = "10s"
    PAGE_OF_SWORDS: str = "ps"
    KNIGHT_OF_SWORDS: str = "ks"
    QUEEN_OF_SWORDS: str = "qs"
    KING_OF_SWORDS: str = "rs"


    ACE_OF_WANDS: str = "aw"
    TWO_OF_WANDS: str = "2w"
    THREE_OF_WANDS: str = "3w"
    FOUR_OF_WANDS: str = "4w"
    FIVE_OF_WANDS: str = "5w"
    SIX_OF_WANDS: str = "6w"
    SEVEN_OF_WANDS: str = "7w"
    EIGHT_OF_WANDS: str = "8w"
    NINE_OF_WANDS: str = "9w"
    TEN_OF_WANDS: str = "10w"
    PAGE_OF_WANDS: str = "pw"
    KNIGHT_OF_WANDS: str = "kw"
    QUEEN_OF_WANDS: str = "qw"
    KING_OF_WANDS: str = "rw"

    @property
    def jpg(self):
        return f"{self.value}.jpg"